# Generated by Django 4.2.7 on 2023-11-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_board_rename_tag_player_name_player_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='label',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
